#!/bin/bash

## Themes
export ROFITHEME="nord"
export BSPBAR="nord"

## Get colors from .Xresources -------------------------------#
focused=$(xrdb ~/.config/X11/xresources -query all | grep color2 | cut -f2)
normal=$(xrdb ~/.config/X11/xresources -query all | grep color8 | cut -f2)

xrdb ~/.config/X11/xresources
getcolors () {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors

## Configurations -------------------------------#
bspc monitor -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII' 'IX'

bspc config border_width 1.00
bspc config window_gap 10
bspc config split_ratio 0.50
bspc config border_radius 1.00

bspc config focused_border_color "$BLUE" 
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true


## Window rules -------------------------------#

# remove all rules first
bspc rule -r *:*

# 2 > web
declare -a web=(firefox firefoxdeveloperedition Chromium)
for i in ${web[@]}; do
     bspc rule -a $i desktop='^2' follow=on focus=on; done

# 3 > file
bspc rule -a Pcmanfm desktop='^3' follow=on focus=on

# 4 > office
declare -a office=(Geany Zathura \
libreoffice-writer libreoffice-calc libreoffice-impress \
libreoffice-startcenter libreoffice Soffice *:libreofficedev *:soffice)
for i in ${office[@]}; do
   bspc rule -a $i desktop='^4' follow=on focus=on; done

# 5 > media
declare -a media=(Audacity mpv Spotify Stremio Inkscape lxmusic Gimp Gimp-2.8)
for i in ${media[@]}; do
   bspc rule -a $i desktop='^5' follow=on focus=on; done

# 6 > settings
declare -a settings=(GParted Lxappearance Lxtask Lxrandr Arandr \
System-config-printer.py Pavucontrol Exo-helper-1)
for i in ${settings[@]}; do
   bspc rule -a $i desktop='^6' state=floating follow=on focus=on; done

# 7 > startup
bspc rule -a qBittorrent desktop='^7' state=floating

# special rules
bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off

declare -a float=(termite Org.gnome.Nautilus Viewnior TelegramDesktop Gedit \ 
Spotify Pcmanfm mpv kitty alacritty zoom)
for i in ${float[@]}; do
   bspc rule -a $i state=floating follow=on focus=on; done
 
## Autostart -------------------------------#

# Kill if already running
killall -9 sxhkd dunst conky xfce4-clipman

# Lauch notification daemon
dunst &
-geom "280x50-10+40" -frame_width "1" -font "Iosevka Custom 9" \
-lb "$BACKGROUND" -lf "$FOREGROUND" -lfr "$BLUE" \
-nb "$BACKGROUND" -nf "$FOREGROUND" -nfr "$BLUE" \
-cb "$BACKGROUND" -cf "$RED" -cfr "$RED" &

# Launch keybindings daemon
sxhkd &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Fix cursor
xsetroot -cursor_name left_ptr &

# Restore wallpaper
nitrogen --set-zoom-fill $HOME/Dotfiles/wallpapers/waifu-norded.png &

# Start clipboard manager
greenclip daemon &

# Start bspwm scripts
bspcolors
bspcomp
bspbar
bspfloat &

# Conky scripts
conky.sh &

# Polkit
exec /usr/bin/polkit-dumb-agent &
